name: "mdm"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ./../:/rails

    # Overrides default command so things don't shut down after the process ends.
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - redis
    - mysql

  redis:
    image: redis:7.2
    volumes:
    - redis-data:/data
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_URL: redis://redis:6379/1

  mysql:
    image: mysql/mysql-server:8.0
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: "%"
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - default

volumes:
  redis-data:
  mysql-data:
