---
:queues:
  - [critical, 5]
  - [default, 3]
  - [mailers, 2]
  - [data_processing, 1]

:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || ENV["RAILS_MAX_THREADS"] || 5 %>


:scheduler:
  :schedule:
    old_data_cleanup:
      cron: "0 0 * * 0"  # Every sunday
      class: "OldDataCleanupJob"

    database_backup:
      cron: "0 2 * * *"  # Every day at 2A.M
      class: "DatabaseBackupJob"
